// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using ArmyTechTask.Models;
using ArmyTechTask.DataAccess.FluentApiConfig;

#nullable disable

namespace ArmyTechTask.DataAccess
{
    public partial class AppDbContext : DbContext
    {
        public AppDbContext()
        {
        }

        public AppDbContext(DbContextOptions<AppDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Branches> Branches { get; set; }
        public virtual DbSet<Cashier> Cashier { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<InvoiceDetails> InvoiceDetails { get; set; }
        public virtual DbSet<InvoiceHeader> InvoiceHeader { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            // FluentApiConfigurations
            modelBuilder.ApplyConfiguration(new BranchesConfig());
            modelBuilder.ApplyConfiguration(new CashierConfig());
            modelBuilder.ApplyConfiguration(new CitiesConfig());
            modelBuilder.ApplyConfiguration(new InvoiceDetailsConfig());
            modelBuilder.ApplyConfiguration(new InvoiceHeaderConfig());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}