// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
//using Microsoft.EntityFrameworkCore;

namespace ArmyTechTask.Models
{
    public partial class InvoiceDetails
    {
        [Key]
        [Column("ID")]
        public long Id { get; set; }

        [Column("InvoiceHeaderID")]
        public long InvoiceHeaderId { get; set; }

        [Required]
        [StringLength(200)]
        public string ItemName { get; set; }

        public double ItemCount { get; set; }

        public double ItemPrice { get; set; }

        [ForeignKey(nameof(InvoiceHeaderId))]
        [InverseProperty("InvoiceDetails")]
        public virtual InvoiceHeader InvoiceHeader { get; set; }
    }
}